package Visual;

import Class.Log;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.Timer;
import javax.swing.UIManager;

public class Login extends javax.swing.JFrame {

    int xMouse, yMouse;

    Log b = new Log();

    private static Login instance;

    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Login");
        OCULTAR.setVisible(false);
        setIconImage(getIconImage());
    }

    @Override
    public Image getIconImage() {

        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imag/LogoTranss.png"));
        return retValue;
    }

    public static String texto = "";

    public void cuentaRegresiva() {
        int contador = 45;
        while (contador >= 0) {
            try {
                Thread.sleep(1000);
                contador--;
                Tiempo.setText("Tiempo restante: " + contador + " seg");
            } catch (InterruptedException ex) {
                ex.printStackTrace();
            }
        }
        this.dispose(); // Cierra el JFrame de Login
    }

    public static Login getInstance() {
        if (instance == null) {
            instance = new Login();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlBase = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextUser = new javax.swing.JTextField();
        jTextPass = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        VER = new javax.swing.JButton();
        OCULTAR = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        x = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        btnexit = new javax.swing.JPanel();
        Cerrar = new javax.swing.JLabel();
        Tiempo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PnlBase.setBackground(new java.awt.Color(102, 102, 102));
        PnlBase.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imag/LogoTranss.png"))); // NOI18N
        PnlBase.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 168));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USUARIO");
        PnlBase.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CONTRASEÑA");
        PnlBase.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 130, -1));

        jTextUser.setBackground(new java.awt.Color(102, 102, 102));
        jTextUser.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextUser.setForeground(new java.awt.Color(204, 204, 204));
        jTextUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextUser.setText("Ingrese Usuario");
        jTextUser.setBorder(null);
        jTextUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextUserMousePressed(evt);
            }
        });
        jTextUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextUserKeyPressed(evt);
            }
        });
        PnlBase.add(jTextUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 200, 30));

        jTextPass.setBackground(new java.awt.Color(102, 102, 102));
        jTextPass.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextPass.setForeground(new java.awt.Color(204, 204, 204));
        jTextPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextPass.setText("********");
        jTextPass.setBorder(null);
        jTextPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextPassMousePressed(evt);
            }
        });
        jTextPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextPassKeyPressed(evt);
            }
        });
        PnlBase.add(jTextPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 200, 30));

        btnIngresar.setBackground(new java.awt.Color(51, 51, 51));
        btnIngresar.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(153, 255, 255));
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        PnlBase.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 100, -1));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        PnlBase.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 200, 20));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        PnlBase.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 200, 30));

        VER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imag/eye_visible_hide_hidden_show_icon_145988.png"))); // NOI18N
        VER.setBorder(null);
        VER.setContentAreaFilled(false);
        VER.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VERMouseClicked(evt);
            }
        });
        PnlBase.add(VER, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 40, 30));

        OCULTAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imag/eye_slash_visible_hide_hidden_show_icon_145987.png"))); // NOI18N
        OCULTAR.setBorder(null);
        OCULTAR.setContentAreaFilled(false);
        OCULTAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OCULTAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OCULTARMouseClicked(evt);
            }
        });
        PnlBase.add(OCULTAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 40, 30));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LOGIN");
        PnlBase.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 90, -1));

        x.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PnlBase.add(x, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 200, 20));

        getContentPane().add(PnlBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 330, 520));

        Header.setBackground(new java.awt.Color(0, 51, 51));
        Header.setForeground(new java.awt.Color(102, 102, 102));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        btnexit.setBackground(new java.awt.Color(0, 51, 51));
        btnexit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cerrar.setBackground(new java.awt.Color(255, 255, 255));
        Cerrar.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        Cerrar.setForeground(new java.awt.Color(255, 255, 255));
        Cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cerrar.setText("X");
        Cerrar.setToolTipText("");
        Cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CerrarMouseExited(evt);
            }
        });
        btnexit.add(Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        Tiempo.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        Tiempo.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addComponent(Tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(btnexit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addComponent(btnexit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(Tiempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        if (jTextUser.getText().equals("") || String.valueOf(jTextPass.getPassword()).equals("")) {
            x.setText("Uno o más campos vacios.");
            Timer timer = new Timer(5000, e -> {
                x.setText("");
                ((Timer) e.getSource()).stop();
            });
            timer.start();
        } else {
            texto = jTextUser.getText();
            if (Log.loginBD(jTextUser, jTextPass)) {

            } else {
                x.setText(Log.L);
                Timer timer = new Timer(5000, e -> {
                    x.setText("");
                    ((Timer) e.getSource()).stop();
                });
                timer.start();
            }

        }


    }//GEN-LAST:event_btnIngresarActionPerformed

    private void jTextUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextUserMousePressed
        if (jTextUser.getText().equals("Ingrese Usuario")) {
            jTextUser.setText("");
            jTextUser.setForeground(Color.black);

        }
        if (String.valueOf(jTextPass.getPassword()).isEmpty()) {
            jTextPass.setText("********");
            jTextPass.setForeground(Color.gray);

        }
    }//GEN-LAST:event_jTextUserMousePressed

    private void jTextPassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextPassMousePressed
        if (String.valueOf(jTextPass.getPassword()).equals("********")) {
            jTextPass.setText("");
            jTextPass.setForeground(Color.black);

        }
        if (jTextUser.getText().isEmpty()) {
            jTextUser.setText("Ingrese Usuario");
            jTextUser.setForeground(Color.gray);

        }
    }//GEN-LAST:event_jTextPassMousePressed

    private void VERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VERMouseClicked
        VER.setVisible(false);
        OCULTAR.setVisible(true);
        jTextPass.setEchoChar((char) 0);
    }//GEN-LAST:event_VERMouseClicked

    private void OCULTARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OCULTARMouseClicked
        VER.setVisible(true);
        OCULTAR.setVisible(false);
        jTextPass.setEchoChar('*');
    }//GEN-LAST:event_OCULTARMouseClicked

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_HeaderMouseDragged

    private void CerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CerrarMouseClicked

    private void CerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseEntered
        btnexit.setBackground(Color.red);
    }//GEN-LAST:event_CerrarMouseEntered

    private void CerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseExited
        btnexit.setBackground(new Color(0, 51, 51));
    }//GEN-LAST:event_CerrarMouseExited

    private void jTextUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextUserKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextPass.requestFocus();
            jTextPass.setText("");
            jTextPass.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextUserKeyPressed

    private void jTextPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPassKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (jTextUser.getText().equals("") || String.valueOf(jTextPass.getPassword()).equals("")) {
                x.setText("Uno o más campos vacios.");
                Timer timer = new Timer(5000, e -> {
                    x.setText("");
                    ((Timer) e.getSource()).stop();
                });
                timer.start();
            } else {
                texto = jTextUser.getText();
                if (Log.loginBD(jTextUser, jTextPass)) {

                } else {
                    x.setText(Log.L);
                    Timer timer = new Timer(5000, e -> {
                        x.setText("");
                        ((Timer) e.getSource()).stop();
                    });
                    timer.start();
                }

            }

        }
    }//GEN-LAST:event_jTextPassKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    UIManager.put("nimbusBlueGrey", new Color(0, 51, 51));
                    UIManager.put("OptionPane.messageFont", new Font("Tahoma", Font.PLAIN, 14));
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            Login login = new Login();
            login.setVisible(true);
            new Thread(() -> {
                login.cuentaRegresiva();
            }).start();
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cerrar;
    private javax.swing.JPanel Header;
    private javax.swing.JButton OCULTAR;
    private javax.swing.JPanel PnlBase;
    private javax.swing.JLabel Tiempo;
    private javax.swing.JButton VER;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JPanel btnexit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPasswordField jTextPass;
    private javax.swing.JTextField jTextUser;
    public javax.swing.JLabel x;
    // End of variables declaration//GEN-END:variables

}
