package Visual;


import desplazable.Desface;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import paneles.CambiaPanel;
import paneles.pnlAdmin;
import paneles.pnlAl;
import paneles.pnlCuar;
import paneles.pnlHome;
import paneles.pnlServ;
import paneles.pnlUser;
import paneles.pnlin;

public class Menu extends javax.swing.JFrame {

   
    private CambiaPanel ad;
    
    int xMouse, yMouse;
    
    Desface desplace;
    Desface desplace1;
    
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Menu");
        ad = new CambiaPanel(pnlPrincipal, new pnlHome());
        setIconImage(getIconImage());
        desplace = new Desface();
        desplace1 = new Desface();
    }
    

 
    
    
    @Override
    public Image getIconImage (){
        
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imag/LogoTranss.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        PnlCerrar = new javax.swing.JPanel();
        Cerrar = new javax.swing.JLabel();
        PnlMin = new javax.swing.JPanel();
        Min = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnUser = new rsbuttom.RSButtonMetro();
        btnIn = new rsbuttom.RSButtonMetro();
        btnServ = new rsbuttom.RSButtonMetro();
        btnCuar = new rsbuttom.RSButtonMetro();
        btnAl = new rsbuttom.RSButtonMetro();
        btnAD = new rsbuttom.RSButtonMetro();
        pnlPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(102, 102, 102));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imag/menu.png"))); // NOI18N
        jButton1.setToolTipText("Ocultar menu");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        PnlCerrar.setBackground(new java.awt.Color(102, 102, 102));
        PnlCerrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imag/Imagen17.png"))); // NOI18N
        Cerrar.setToolTipText("Cerrar sesión ");
        Cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CerrarMouseExited(evt);
            }
        });
        PnlCerrar.add(Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 6, 50, -1));

        PnlMin.setBackground(new java.awt.Color(102, 102, 102));
        PnlMin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Min.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imag/min.png"))); // NOI18N
        Min.setToolTipText("Minimizar");
        Min.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Min.setPreferredSize(new java.awt.Dimension(47, 47));
        Min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinMouseExited(evt);
            }
        });
        PnlMin.add(Min, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 30, -1));

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(749, 749, 749)
                .addComponent(PnlMin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PnlCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jButton1))
                    .addComponent(PnlCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(PnlMin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(3, 3, 3))
        );

        jPanel1.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 57));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADMINISTRACION");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(10, 310, 190, 29);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MENU");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        jPanel3.add(jLabel2);
        jLabel2.setBounds(10, 20, 90, 43);

        btnUser.setBackground(new java.awt.Color(0, 0, 0));
        btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imag/Imagen11.png"))); // NOI18N
        btnUser.setText("Usuarios");
        btnUser.setColorHover(new java.awt.Color(204, 204, 204));
        btnUser.setColorNormal(new java.awt.Color(0, 0, 0));
        btnUser.setColorPressed(new java.awt.Color(153, 153, 153));
        btnUser.setColorTextHover(new java.awt.Color(0, 0, 153));
        btnUser.setColorTextPressed(new java.awt.Color(0, 0, 0));
        btnUser.setIconTextGap(10);
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });
        jPanel3.add(btnUser);
        btnUser.setBounds(0, 440, 200, 35);

        btnIn.setBackground(new java.awt.Color(0, 0, 0));
        btnIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imag/Imagen12_1.png"))); // NOI18N
        btnIn.setText("Inquilinos");
        btnIn.setColorHover(new java.awt.Color(204, 204, 204));
        btnIn.setColorNormal(new java.awt.Color(0, 0, 0));
        btnIn.setColorPressed(new java.awt.Color(153, 153, 153));
        btnIn.setColorTextHover(new java.awt.Color(0, 0, 153));
        btnIn.setColorTextPressed(new java.awt.Color(0, 0, 0));
        btnIn.setIconTextGap(10);
        btnIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInActionPerformed(evt);
            }
        });
        jPanel3.add(btnIn);
        btnIn.setBounds(0, 90, 200, 35);

        btnServ.setBackground(new java.awt.Color(0, 0, 0));
        btnServ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imag/Imagen41.png"))); // NOI18N
        btnServ.setText("Servicios");
        btnServ.setColorHover(new java.awt.Color(204, 204, 204));
        btnServ.setColorNormal(new java.awt.Color(0, 0, 0));
        btnServ.setColorPressed(new java.awt.Color(153, 153, 153));
        btnServ.setColorTextHover(new java.awt.Color(0, 0, 153));
        btnServ.setColorTextPressed(new java.awt.Color(0, 0, 0));
        btnServ.setIconTextGap(10);
        btnServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServActionPerformed(evt);
            }
        });
        jPanel3.add(btnServ);
        btnServ.setBounds(0, 140, 200, 35);

        btnCuar.setBackground(new java.awt.Color(0, 0, 0));
        btnCuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imag/Imagen31.png"))); // NOI18N
        btnCuar.setText("Cuartos");
        btnCuar.setColorHover(new java.awt.Color(204, 204, 204));
        btnCuar.setColorNormal(new java.awt.Color(0, 0, 0));
        btnCuar.setColorPressed(new java.awt.Color(153, 153, 153));
        btnCuar.setColorTextHover(new java.awt.Color(0, 0, 153));
        btnCuar.setColorTextPressed(new java.awt.Color(0, 0, 0));
        btnCuar.setIconTextGap(10);
        btnCuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuarActionPerformed(evt);
            }
        });
        jPanel3.add(btnCuar);
        btnCuar.setBounds(0, 190, 200, 35);

        btnAl.setBackground(new java.awt.Color(0, 0, 0));
        btnAl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imag/Imagen21.png"))); // NOI18N
        btnAl.setText("Alquiler");
        btnAl.setColorHover(new java.awt.Color(204, 204, 204));
        btnAl.setColorNormal(new java.awt.Color(0, 0, 0));
        btnAl.setColorPressed(new java.awt.Color(153, 153, 153));
        btnAl.setColorTextHover(new java.awt.Color(0, 0, 153));
        btnAl.setColorTextPressed(new java.awt.Color(0, 0, 0));
        btnAl.setIconTextGap(10);
        btnAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlActionPerformed(evt);
            }
        });
        jPanel3.add(btnAl);
        btnAl.setBounds(0, 240, 200, 35);

        btnAD.setBackground(new java.awt.Color(0, 0, 0));
        btnAD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imag/admin12.png"))); // NOI18N
        btnAD.setText("Admin");
        btnAD.setColorHover(new java.awt.Color(204, 204, 204));
        btnAD.setColorNormal(new java.awt.Color(0, 0, 0));
        btnAD.setColorPressed(new java.awt.Color(153, 153, 153));
        btnAD.setColorTextHover(new java.awt.Color(0, 0, 153));
        btnAD.setColorTextPressed(new java.awt.Color(0, 0, 0));
        btnAD.setIconTextGap(10);
        btnAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADActionPerformed(evt);
            }
        });
        jPanel3.add(btnAD);
        btnAD.setBounds(0, 380, 200, 35);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 57, 200, 580));

        pnlPrincipal.setBackground(new java.awt.Color(204, 204, 204));
        pnlPrincipal.setLayout(new javax.swing.BoxLayout(pnlPrincipal, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.add(pnlPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 720, 580));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jPanel3.getX() == 0) {
            desplace.desplazarIzquierda(jPanel3, jPanel3.getX(), -300, 20, 10);
            desplace1.desplazarIzquierda(pnlPrincipal, pnlPrincipal.getX(), 100, 20, 10);
        } else if (jPanel3.getX() == -300) {
            desplace.desplazarDerecha(jPanel3, jPanel3.getX(), 0, 15, 10);
            desplace1.desplazarDerecha(pnlPrincipal, pnlPrincipal.getX(), 260, 20, 10);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInActionPerformed
        btnIn.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        ad = new CambiaPanel(pnlPrincipal, new pnlin());
        btnIn.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnInActionPerformed

    private void btnServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServActionPerformed
        btnServ.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        ad = new CambiaPanel(pnlPrincipal, new pnlServ());
        btnServ.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnServActionPerformed

    private void btnCuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuarActionPerformed
        btnCuar.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        ad = new CambiaPanel(pnlPrincipal, new pnlCuar());
        btnCuar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnCuarActionPerformed

    private void btnAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlActionPerformed
        btnAl.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        ad = new CambiaPanel(pnlPrincipal, new pnlAl());
        btnAl.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnAlActionPerformed

    private void CerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseClicked
        Login b = new Login();
        int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro de cerrar sesión?", "Alerta!", JOptionPane.YES_NO_OPTION);
        if (resp == JOptionPane.YES_OPTION) {
            this.dispose();
            java.awt.EventQueue.invokeLater(() -> {
                Login login = Login.getInstance(); // obtiene la instancia actual del Login
                login.setVisible(true);
                new Thread(() -> {
                    login.cuentaRegresiva();
                }).start();
            });
            

        }
    }//GEN-LAST:event_CerrarMouseClicked

    private void CerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseEntered
        PnlCerrar.setBackground(Color.RED);
    }//GEN-LAST:event_CerrarMouseEntered

    private void CerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseExited
        PnlCerrar.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_CerrarMouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        jLabel2.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        ad = new CambiaPanel(pnlPrincipal, new pnlHome());
        jLabel2.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        jLabel2.setForeground(Color.BLUE);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
       jLabel2.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel2MouseExited

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_HeaderMouseDragged

    private void btnADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADActionPerformed
        btnAD.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        ad = new CambiaPanel(pnlPrincipal, new pnlAdmin());
        btnAD.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnADActionPerformed

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        btnUser.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        ad = new CambiaPanel(pnlPrincipal, new pnlUser());
        btnUser.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnUserActionPerformed

    private void MinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_MinMouseClicked

    private void MinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinMouseEntered
        PnlMin.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_MinMouseEntered

    private void MinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinMouseExited
        PnlMin.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_MinMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    UIManager.put("nimbusBlueGrey", new Color(0, 51, 51));
                    UIManager.put("OptionPane.messageFont", new Font("Tahoma", Font.PLAIN, 14));  
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new splashscreen.SplashScreen(null, true).setVisible(true);
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cerrar;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel Min;
    private javax.swing.JPanel PnlCerrar;
    private javax.swing.JPanel PnlMin;
    private rsbuttom.RSButtonMetro btnAD;
    private rsbuttom.RSButtonMetro btnAl;
    private rsbuttom.RSButtonMetro btnCuar;
    private rsbuttom.RSButtonMetro btnIn;
    private rsbuttom.RSButtonMetro btnServ;
    private rsbuttom.RSButtonMetro btnUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
