package paneles;

import Class.VerfPIN;
import Visual.Contrato;
import Visual.Login;
import Visual.ReFa;
import java.awt.Color;
import javax.swing.JOptionPane;
import org.apache.log4j.PropertyConfigurator;


public class pnlAdmin extends javax.swing.JPanel { 
    
    public pnlAdmin() {
        initComponents();

    }

    
 
    public void Confirmacion() {
        Login a = new Login();
        int resp = JOptionPane.showConfirmDialog(this, "Estas entrado a un sitio que solo puede entrar administradores.\n"
                + "Lo pediremos " + a.texto + " que se indentifique con su PIN que le llegara a su numero de celular.", "Advertencia", JOptionPane.YES_NO_OPTION);

        if (resp == JOptionPane.YES_OPTION) {
            PropertyConfigurator.configure("src/model/log4j.properties");
            new VerfPIN().SMSPIN();

        } else {

        }
    }


  
    public void Confirmacion2() {
        Login a = new Login();
        int resp = JOptionPane.showConfirmDialog(this, "Estas entrado a un sitio que solo puede entrar administradores.\n"
                + "Lo pediremos " + a.texto + " que se indentifique con su contraseña", "Advertencia", JOptionPane.YES_NO_OPTION);
        if (resp == JOptionPane.YES_OPTION) {

            PropertyConfigurator.configure("src/model/log4j.properties");
            new VerfPIN().SMSPIN2();

        } else {
            JOptionPane.showMessageDialog(this, "Crendenciales incorrectas.");
        }
    }



  
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFac = new javax.swing.JPanel();
        Factura = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnlCon = new javax.swing.JPanel();
        Contrato = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnlDeta = new javax.swing.JPanel();
        AlqDetallado = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlHis = new javax.swing.JPanel();
        Archivo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        pnlFac.setBackground(new java.awt.Color(187, 187, 187));

        Factura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imag/propagation_calculator_calc_6110.png"))); // NOI18N
        Factura.setToolTipText("Boleta y Facturas de Alquileres");
        Factura.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Factura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FacturaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FacturaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FacturaMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Facturacion de Alquileres");

        javax.swing.GroupLayout pnlFacLayout = new javax.swing.GroupLayout(pnlFac);
        pnlFac.setLayout(pnlFacLayout);
        pnlFacLayout.setHorizontalGroup(
            pnlFacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFacLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(Factura)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
        );
        pnlFacLayout.setVerticalGroup(
            pnlFacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFacLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(Factura)
                .addGap(75, 75, 75))
        );

        pnlCon.setBackground(new java.awt.Color(187, 187, 187));

        Contrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imag/organizer_calendar_pen_note_6134.png"))); // NOI18N
        Contrato.setToolTipText("Contrato de Alquileres");
        Contrato.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Contrato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContratoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ContratoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ContratoMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Contrato de Alquileres");

        javax.swing.GroupLayout pnlConLayout = new javax.swing.GroupLayout(pnlCon);
        pnlCon.setLayout(pnlConLayout);
        pnlConLayout.setHorizontalGroup(
            pnlConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Contrato)
                .addGap(150, 150, 150))
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
        );
        pnlConLayout.setVerticalGroup(
            pnlConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(Contrato)
                .addGap(69, 69, 69))
        );

        pnlDeta.setBackground(new java.awt.Color(187, 187, 187));

        AlqDetallado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imag/bootloader_users_person_people_6080.png"))); // NOI18N
        AlqDetallado.setToolTipText("Detalle de Alquileres");
        AlqDetallado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AlqDetallado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AlqDetalladoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AlqDetalladoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AlqDetalladoMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Reprogramacion de Fecha");

        javax.swing.GroupLayout pnlDetaLayout = new javax.swing.GroupLayout(pnlDeta);
        pnlDeta.setLayout(pnlDetaLayout);
        pnlDetaLayout.setHorizontalGroup(
            pnlDetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetaLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(AlqDetallado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
        );
        pnlDetaLayout.setVerticalGroup(
            pnlDetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDetaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(AlqDetallado)
                .addGap(74, 74, 74))
        );

        pnlHis.setBackground(new java.awt.Color(187, 187, 187));

        Archivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imag/Managerfiles_historyfiles_administradordearchivos_6225.png"))); // NOI18N
        Archivo.setToolTipText("Archivo de Alquileres");
        Archivo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Archivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ArchivoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ArchivoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ArchivoMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Archivo de Alquileres");

        javax.swing.GroupLayout pnlHisLayout = new javax.swing.GroupLayout(pnlHis);
        pnlHis.setLayout(pnlHisLayout);
        pnlHisLayout.setHorizontalGroup(
            pnlHisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHisLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(Archivo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
        );
        pnlHisLayout.setVerticalGroup(
            pnlHisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(Archivo)
                .addGap(74, 74, 74))
        );

        jLabel1.setFont(new java.awt.Font("Constantia", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Administracion");

        jLabel6.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Zona exclusiva solo para Administradores");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlHis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(pnlFac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlDeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(pnlCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlHis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlFac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jLabel6))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ArchivoMouseClicked
        Confirmacion();
    }//GEN-LAST:event_ArchivoMouseClicked

    private void ArchivoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ArchivoMouseEntered
       pnlHis.setBackground(new Color(102,153,255));
    }//GEN-LAST:event_ArchivoMouseEntered

    private void ArchivoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ArchivoMouseExited
        pnlHis.setBackground(new Color(187,187,187));
    }//GEN-LAST:event_ArchivoMouseExited

    private void FacturaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FacturaMouseEntered
        pnlFac.setBackground(new Color(102,153,255));
    }//GEN-LAST:event_FacturaMouseEntered

    private void FacturaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FacturaMouseExited
        pnlFac.setBackground(new Color(187,187,187));
    }//GEN-LAST:event_FacturaMouseExited

    private void ContratoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContratoMouseEntered
        pnlCon.setBackground(new Color(102,153,255));
    }//GEN-LAST:event_ContratoMouseEntered

    private void ContratoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContratoMouseExited
        pnlCon.setBackground(new Color(187,187,187));
    }//GEN-LAST:event_ContratoMouseExited

    private void AlqDetalladoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlqDetalladoMouseEntered
        pnlDeta.setBackground(new Color(102,153,255));
    }//GEN-LAST:event_AlqDetalladoMouseEntered

    private void AlqDetalladoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlqDetalladoMouseExited
        pnlDeta.setBackground(new Color(187,187,187));
    }//GEN-LAST:event_AlqDetalladoMouseExited

    private void AlqDetalladoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlqDetalladoMouseClicked
        Confirmacion2();
    }//GEN-LAST:event_AlqDetalladoMouseClicked

    private void FacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FacturaMouseClicked
       ReFa rf = new ReFa();
       rf.setVisible(true);
    }//GEN-LAST:event_FacturaMouseClicked

    private void ContratoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContratoMouseClicked
        Contrato con = new Contrato();
        con.setVisible(true);
    }//GEN-LAST:event_ContratoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel AlqDetallado;
    public javax.swing.JLabel Archivo;
    public javax.swing.JLabel Contrato;
    public javax.swing.JLabel Factura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pnlCon;
    private javax.swing.JPanel pnlDeta;
    private javax.swing.JPanel pnlFac;
    private javax.swing.JPanel pnlHis;
    // End of variables declaration//GEN-END:variables
}
