package paneles;

import Class.Del;
import DataBase.ConexionBD;
import Visual.AddInq;
import Visual.ModAL;
import java.awt.Color;
import java.awt.Font;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;


public class pnlAl extends javax.swing.JPanel {

    public void TablaLimpia(){
        visor.getColumnModel().getColumn(0).setResizable(false);
        visor.getColumnModel().getColumn(1).setResizable(false);
        visor.getColumnModel().getColumn(2).setResizable(false);
        visor.getColumnModel().getColumn(3).setResizable(false);
        visor.getColumnModel().getColumn(4).setResizable(false);
        visor.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        visor.getTableHeader().setOpaque(false);
        visor.getTableHeader().setBackground(new Color(0, 51, 51));
        visor.getTableHeader().setForeground(Color.WHITE);
        visor.setRowHeight(25);
    }
    
    public static String inf_in = "";
    
    public pnlAl() {
        initComponents();
        mostrar3("Alquiler");
        TablaLimpia();
        visor.addMouseListener(new MouseAdapter(){
            @Override
            public void mousePressed(MouseEvent Mouse_evt){
                JTable table = (JTable) Mouse_evt.getSource();
                Point point = Mouse_evt.getPoint();
                int row = table.rowAtPoint(point);
                if(Mouse_evt.getClickCount() == 1){
                    jTextId_Al.setText(visor.getValueAt(visor.getSelectedRow(), 0).toString());                   
                } if(Mouse_evt.getClickCount() == 2){
                    inf_in = (String)visor.getValueAt(visor.getSelectedRow(), 0);
                    ModAL mod = new ModAL();
                    mod.setVisible(true);
                    mod.jTextId_Al.setText(visor.getValueAt(visor.getSelectedRow(), 0).toString());
                    mod.jTextId_in.setText(visor.getValueAt(visor.getSelectedRow(), 1).toString());
                    mod.jTextId_Arr.setText(visor.getValueAt(visor.getSelectedRow(), 2).toString());
                    mod.jTextId_Serv.setText(visor.getValueAt(visor.getSelectedRow(), 3).toString());
                    mod.jTextId_Cuar.setText(visor.getValueAt(visor.getSelectedRow(), 4).toString());
                }
            }
        });
        
        
    }

     public void mostrar3(String tabla){
        String sql = "select Id_Al, Id_In, Id_Arre, Id_Serv, Id_Cuar from " + tabla;
        Statement st;
        ConexionBD con = new ConexionBD();
        Connection DBConexion = con.getConnection();  
        System.out.println(sql);
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Cod.Alquiler");
        model.addColumn("Cod.Inquilino");
        model.addColumn("Cod.Dueño");
        model.addColumn("Cod.Servicio");
        model.addColumn("Cod.Cuarto");
        visor.setModel(model);
        
        String [] datos = new String[5];
        try{
            st = DBConexion.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next())
               {
                   datos[0]=rs.getString(1);
                   datos[1]=rs.getString(2);
                   datos[2]=rs.getString(3);
                   datos[3]=rs.getString(4);
                   datos[4]=rs.getString(5);
                   model.addRow(datos);
               } 
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "ERROR" + e.toString());
            
        }
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnEli = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        visor = new javax.swing.JTable();
        btnIn = new javax.swing.JButton();
        jTextId_Al = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Text = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(732, 512));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cuadro de Alquileres");

        btnEli.setBackground(new java.awt.Color(0, 0, 0));
        btnEli.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnEli.setForeground(new java.awt.Color(255, 255, 255));
        btnEli.setText("Eliminar");
        btnEli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliMouseExited(evt);
            }
        });
        btnEli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliActionPerformed(evt);
            }
        });

        visor = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int col){
                return false;
            }
        };
        visor.setBackground(new java.awt.Color(255, 255, 255));
        visor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        visor.setForeground(new java.awt.Color(0, 0, 0));
        visor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        visor.setFocusable(false);
        visor.setIntercellSpacing(new java.awt.Dimension(0, 0));
        visor.setRowHeight(25);
        visor.setSelectionBackground(new java.awt.Color(0, 0, 51));
        visor.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(visor);

        btnIn.setBackground(new java.awt.Color(0, 0, 0));
        btnIn.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnIn.setForeground(new java.awt.Color(255, 255, 255));
        btnIn.setText("Ingresar");
        btnIn.setToolTipText("");
        btnIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInMouseExited(evt);
            }
        });
        btnIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInActionPerformed(evt);
            }
        });

        jTextId_Al.setEditable(false);
        jTextId_Al.setBackground(new java.awt.Color(204, 204, 204));
        jTextId_Al.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextId_Al.setForeground(new java.awt.Color(204, 204, 204));
        jTextId_Al.setToolTipText("");
        jTextId_Al.setBorder(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imag/arrow_refresh_15732 (2).png"))); // NOI18N
        jButton1.setToolTipText("Actualizar");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Text.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Text.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(Text, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157)
                .addComponent(jTextId_Al, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174)
                .addComponent(btnIn))
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(542, 542, 542)
                .addComponent(btnEli))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Text, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextId_Al, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnIn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton1))
                    .addComponent(btnEli, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
      
        jButton1.setContentAreaFilled(true);
        jButton1.setBackground(Color.cyan);
        
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        
        jButton1.setContentAreaFilled(false);
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mostrar3("Alquiler");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInActionPerformed
       AddInq in = new AddInq();
       in.setVisible(true);
       
    }//GEN-LAST:event_btnInActionPerformed

    private void btnEliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliActionPerformed
        Del d = new Del();
        if (d.delete_Al(jTextId_Al)) {
            Text.setText("Se elimino correctemente");
            mostrar3("Alquiler");
            Timer timer = new Timer(5000, e -> {
                Text.setText("");
                ((Timer) e.getSource()).stop();
            });
            timer.start();
        } else {
            Text.setText("Error al eliminar");
            Timer timer = new Timer(5000, e -> {
                Text.setText("");
                ((Timer) e.getSource()).stop();
            });
            timer.start();
        }
    }//GEN-LAST:event_btnEliActionPerformed

    private void btnInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInMouseEntered
        btnIn.setBackground(Color.BLUE);
    }//GEN-LAST:event_btnInMouseEntered

    private void btnInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInMouseExited
        btnIn.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_btnInMouseExited

    private void btnEliMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliMouseEntered
        btnEli.setBackground(Color.RED);
    }//GEN-LAST:event_btnEliMouseEntered

    private void btnEliMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliMouseExited
        btnEli.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_btnEliMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text;
    private javax.swing.JButton btnEli;
    private javax.swing.JButton btnIn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextId_Al;
    private javax.swing.JTable visor;
    // End of variables declaration//GEN-END:variables
}
