package paneles;

import Class.Add;
import org.apache.log4j.PropertyConfigurator;
import Class.Boleto;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

public class pnlBol extends javax.swing.JPanel {

    public pnlBol() {
        initComponents();
    }
 
    public static String inq = "";
    public static String Cant = "";
    public static String Mot = "";
    public static String Dia = "";
    public static String Mes = "";
    public static String Año = "";
    public static String Nre = "";
    
    public void gif() {
        ImageIcon check_gif = new ImageIcon("src/Imag/carga.gif");
        ImageIcon resizedIcon = new ImageIcon(check_gif.getImage().getScaledInstance(85, 85, Image.SCALE_DEFAULT));
        JOptionPane optionPane = new JOptionPane("Entrado a vista previa.", JOptionPane.PLAIN_MESSAGE, JOptionPane.DEFAULT_OPTION, resizedIcon, new Object[]{}, null);
        JDialog dialog = optionPane.createDialog("Information");
        ImageIcon customIcon = new ImageIcon("src/Imag/LogoTranss.png");
        Image image = customIcon.getImage();
        dialog.setIconImage(image);
        dialog.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        dialog.setVisible(true);
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TextNre = new javax.swing.JTextField();
        TextInq = new javax.swing.JTextField();
        TextCant = new javax.swing.JTextField();
        TextMot = new javax.swing.JTextField();
        TextDia = new javax.swing.JTextField();
        TextMes = new javax.swing.JTextField();
        Textaño = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnRe = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(865, 401));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Constantia", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Recibo de Inquilino");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 865, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("N°Recibo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 55, 85, -1));

        jLabel3.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre Inquilino(a):");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 109, -1, -1));

        jLabel4.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Cantidad de :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 148, -1, -1));

        jLabel5.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Por Motivo de :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 183, 150, -1));

        TextNre.setBackground(new java.awt.Color(255, 255, 255));
        TextNre.setForeground(new java.awt.Color(0, 0, 0));
        TextNre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextNreKeyTyped(evt);
            }
        });
        jPanel1.add(TextNre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 72, -1));

        TextInq.setBackground(new java.awt.Color(255, 255, 255));
        TextInq.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(TextInq, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 106, 412, -1));

        TextCant.setBackground(new java.awt.Color(255, 255, 255));
        TextCant.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(TextCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 145, 181, -1));

        TextMot.setBackground(new java.awt.Color(255, 255, 255));
        TextMot.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(TextMot, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 450, -1));

        TextDia.setBackground(new java.awt.Color(255, 255, 255));
        TextDia.setForeground(new java.awt.Color(0, 0, 0));
        TextDia.setToolTipText("Dia");
        TextDia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextDiaKeyTyped(evt);
            }
        });
        jPanel1.add(TextDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 40, -1));

        TextMes.setBackground(new java.awt.Color(255, 255, 255));
        TextMes.setForeground(new java.awt.Color(0, 0, 0));
        TextMes.setToolTipText("Mes");
        jPanel1.add(TextMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 87, -1));

        Textaño.setBackground(new java.awt.Color(255, 255, 255));
        Textaño.setForeground(new java.awt.Color(0, 0, 0));
        Textaño.setToolTipText("Año");
        Textaño.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextañoKeyTyped(evt);
            }
        });
        jPanel1.add(Textaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 79, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("de");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 253, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("del");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 253, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Fecha:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 253, -1, -1));

        btnRe.setBackground(new java.awt.Color(204, 204, 204));
        btnRe.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnRe.setForeground(new java.awt.Color(0, 0, 0));
        btnRe.setText("Imprimir Recibo");
        btnRe.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReActionPerformed(evt);
            }
        });
        jPanel1.add(btnRe, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 256, 257, 66));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnReActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReActionPerformed
        inq = TextInq.getText();
        Cant = TextCant.getText();
        Mot = TextMot.getText();
        Dia = TextDia.getText();
        Mes = TextMes.getText();
        Año = Textaño.getText();
        Nre = TextNre.getText();
        Add a = new Add();
        a.add_Recibo(Nre, inq, Cant, Mot, Dia, Mes, Año);
        gif();
        PropertyConfigurator.configure("src/model/log4j.properties");
        Boleto rep2 = new Boleto();
    }//GEN-LAST:event_btnReActionPerformed

    private void TextNreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextNreKeyTyped
        char validar=evt.getKeyChar();
       
       if(Character.isLetter(validar)){
           getToolkit().beep();
           evt.consume();
           
           JOptionPane.showMessageDialog(this, "Este campo solo acepta numeros.");
       }
    }//GEN-LAST:event_TextNreKeyTyped

    private void TextDiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextDiaKeyTyped
        char validar=evt.getKeyChar();
       
       if(Character.isLetter(validar)){
           getToolkit().beep();
           evt.consume();
           
           JOptionPane.showMessageDialog(this, "Este campo solo acepta numeros.");
       }
    }//GEN-LAST:event_TextDiaKeyTyped

    private void TextañoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextañoKeyTyped
        char validar=evt.getKeyChar();
       
       if(Character.isLetter(validar)){
           getToolkit().beep();
           evt.consume();
           
           JOptionPane.showMessageDialog(this, "Este campo solo acepta numeros.");
       }
    }//GEN-LAST:event_TextañoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextCant;
    private javax.swing.JTextField TextDia;
    private javax.swing.JTextField TextInq;
    private javax.swing.JTextField TextMes;
    private javax.swing.JTextField TextMot;
    private javax.swing.JTextField TextNre;
    private javax.swing.JTextField Textaño;
    private javax.swing.JButton btnRe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
