package paneles;

import Class.Del;
import DataBase.ConexionBD;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

public class pnlCobrar extends javax.swing.JPanel {

    
    private void TablaLimpia(){
        visor.getColumnModel().getColumn(0).setResizable(false);
        visor.getColumnModel().getColumn(1).setResizable(false);
        visor.getColumnModel().getColumn(2).setResizable(false);
        visor.getColumnModel().getColumn(3).setResizable(false);
        visor.getColumnModel().getColumn(4).setResizable(false);
        visor.getColumnModel().getColumn(0).setPreferredWidth(5);
        visor.getColumnModel().getColumn(1).setPreferredWidth(360);
        visor.getColumnModel().getColumn(2).setPreferredWidth(35);
        visor.getColumnModel().getColumn(3).setPreferredWidth(35);
        visor.getColumnModel().getColumn(4).setPreferredWidth(15);
        visor.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        visor.getTableHeader().setOpaque(false);
        visor.getTableHeader().setBackground(new Color(0, 51, 51));
        visor.getTableHeader().setForeground(Color.WHITE);
        visor.setRowHeight(25);
    }
    
    
    Calendar calendar = Calendar.getInstance();
    int month = calendar.get(Calendar.MONTH);
    String monthName = calendar.getDisplayName(Calendar.MONTH, Calendar.LONG, Locale.getDefault());
    
    public pnlCobrar() {
        initComponents();
        mostrar("Mes_Pago");
        LabelMes.setText("Cobranza del mes de " + monthName);
        TablaLimpia();
    }

    
    private void mostrar(String tabla){
        String sql = "select * from " + tabla;
        Statement st;
        ConexionBD con = new ConexionBD();
        Connection DBConexion = con.getConnection();  
        System.out.println(sql);
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Codigo");
        model.addColumn("Nombre completo del Inq.");
        model.addColumn("Precio a pagar");
        model.addColumn("Fecha de pago");
        model.addColumn("Seleccione");
        visor.setModel(model);
        
        String [] datos = new String[5];
        addCheckBox(4,visor);
        
        try{
            st = DBConexion.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next())
               {
                   datos[0]=rs.getString(1);
                   datos[1]=rs.getString(2);
                   datos[2]=rs.getString(3);
                   datos[3]=rs.getString(4);
                   model.addRow(datos);
               } 
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "ERROR" + e.toString());
            
        }
    }
    
    public void gif_check() {
        ImageIcon check_gif = new ImageIcon("src/Imag/check.gif");
        ImageIcon resizedIcon = new ImageIcon(check_gif.getImage().getScaledInstance(150, 150, Image.SCALE_DEFAULT));
        JOptionPane optionPane = new JOptionPane("Se registro correctamente el pago.", JOptionPane.PLAIN_MESSAGE, JOptionPane.DEFAULT_OPTION, resizedIcon, new Object[]{}, null);
        JDialog dialog = optionPane.createDialog("Alerta");
        ImageIcon customIcon = new ImageIcon("src/Imag/LogoTranss.png");
        Image image = customIcon.getImage();
        dialog.setIconImage(image);
        dialog.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        dialog.setVisible(true);
        
    }
    
    public void addCheckBox(int column, JTable table) {
        TableColumn tc = table.getColumnModel().getColumn(column);
        tc.setCellEditor(table.getDefaultEditor(Boolean.class));
        tc.setCellRenderer(table.getDefaultRenderer(Boolean.class));
        
    }

    public boolean IsSelected(int row, int column, JTable table) {
        return table.getValueAt(row, column) != null;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        visor = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnPago = new javax.swing.JButton();
        btnPen = new javax.swing.JButton();
        LabelMes = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        visor = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int col){
                if (col <= 3 ){
                    return false;
                }else{
                    return true;
                }

            }

        };
        visor.setBackground(new java.awt.Color(255, 255, 255));
        visor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        visor.setForeground(new java.awt.Color(0, 0, 0));
        visor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        visor.setIntercellSpacing(new java.awt.Dimension(0, 0));
        visor.setRowHeight(25);
        visor.setSelectionBackground(new java.awt.Color(0, 0, 51));
        visor.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(visor);

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Alq. Pediente de Cobranza");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPago.setBackground(new java.awt.Color(0, 51, 102));
        btnPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imag/pay_cash_bill_money_buy_icon_143287.png"))); // NOI18N
        btnPago.setToolTipText("Pago recibido");
        btnPago.setBorder(null);
        btnPago.setContentAreaFilled(false);
        btnPago.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPagoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPagoMouseExited(evt);
            }
        });
        btnPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagoActionPerformed(evt);
            }
        });
        jPanel1.add(btnPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 80, 56));

        btnPen.setBackground(new java.awt.Color(0, 51, 102));
        btnPen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imag/pay_payment_bill_dollar_cash_icon_143281.png"))); // NOI18N
        btnPen.setToolTipText("Pago pendiente");
        btnPen.setBorder(null);
        btnPen.setContentAreaFilled(false);
        btnPen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPenMouseExited(evt);
            }
        });
        btnPen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPenActionPerformed(evt);
            }
        });
        jPanel1.add(btnPen, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 80, 56));

        LabelMes.setFont(new java.awt.Font("Constantia", 1, 36)); // NOI18N
        LabelMes.setForeground(new java.awt.Color(0, 0, 0));
        LabelMes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelMes.setText("Cobraza del Mes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelMes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(LabelMes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagoMouseEntered
        btnPago.setContentAreaFilled(true);
        btnPago.setBackground(new Color(51,255,255));
        btnPago.setBorderPainted(false);
        btnPago.setOpaque(false);
    }//GEN-LAST:event_btnPagoMouseEntered

    private void btnPagoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagoMouseExited
        btnPago.setContentAreaFilled(false);
        btnPago.setBackground(new Color(0,51,102));
    }//GEN-LAST:event_btnPagoMouseExited

    private void btnPenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPenMouseEntered
        btnPen.setContentAreaFilled(true);
        btnPen.setBackground(new Color(51,255,255));
        btnPen.setBorderPainted(false);
        btnPen.setOpaque(false);
    }//GEN-LAST:event_btnPenMouseEntered

    private void btnPenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPenMouseExited
        btnPen.setContentAreaFilled(false);
        btnPen.setBackground(new Color(0,51,102));
    }//GEN-LAST:event_btnPenMouseExited

    private void btnPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagoActionPerformed
        for (int i = 0; i < visor.getRowCount(); i++) {
            if (IsSelected(i, 4, visor)) {
                Del d = new Del();
                d.delete_Mes(Integer.parseInt(visor.getValueAt(i, 0).toString()));
                gif_check();
                mostrar("Mes_Pago");
                TablaLimpia();
            }
        }

    }//GEN-LAST:event_btnPagoActionPerformed

    private void btnPenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenActionPerformed
        JOptionPane.showMessageDialog(null, "Se realizo correctamente el pediente.\n Todo pago que sea marcado como pendiente permanecera \n en cobraza hasta que pague lo establecido.", "Information", JOptionPane.PLAIN_MESSAGE, new ImageIcon("src/Imag/LogoIco.png"));
    }//GEN-LAST:event_btnPenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelMes;
    private javax.swing.JButton btnPago;
    private javax.swing.JButton btnPen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable visor;
    // End of variables declaration//GEN-END:variables
}
